# Generated by Django 5.1.6 on 2025-03-12 03:00

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentname', models.CharField(max_length=150, verbose_name='folder name')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('stored_hours', models.CharField(max_length=20)),
                ('attendees', models.CharField(blank=True, max_length=100, verbose_name='Attendee')),
                ('generated_links', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('event_day', models.CharField(blank=True, max_length=20)),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='FolderNameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=100, verbose_name='Folder Name')),
                ('parentname', models.CharField(max_length=100, verbose_name='Parent Name')),
                ('folderurl', models.CharField(max_length=100, verbose_name='folder Url')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='FolderRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=150, verbose_name='folder name')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posted', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('agenda', models.TextField()),
                ('attendees', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=100, verbose_name='Document Name')),
                ('messageTitle', models.CharField(max_length=100, verbose_name='Message Title')),
                ('messageText', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('SaveToDraft', models.CharField(max_length=100, verbose_name='Save to Draft')),
                ('mydate', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('otpCode', models.CharField(max_length=50, verbose_name='otp')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=100, verbose_name='Document Name')),
                ('tasklist', models.CharField(max_length=200, verbose_name='Task List')),
                ('assignee', models.CharField(max_length=100, verbose_name='Task Assignee')),
                ('taskdetails', models.CharField(max_length=100, verbose_name='Task Details')),
                ('dueon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('mymessage', models.CharField(max_length=200, verbose_name='Message')),
                ('mydate', models.DateTimeField(verbose_name='date_created')),
                ('profile', models.ImageField(upload_to='profile/')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/files/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='File Name')),
                ('foldername', models.CharField(max_length=100, verbose_name='Folder Name')),
                ('parentname', models.CharField(max_length=100, verbose_name='Parent Name')),
                ('folderurl', models.CharField(max_length=100, verbose_name='folder Url')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
                ('docs', models.ImageField(upload_to='repository/static/profile/')),
                ('nameUploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('profile', models.ImageField(upload_to='medias')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
