# Generated by Django 5.1.6 on 2025-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='formatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontSize', models.CharField(max_length=50, verbose_name='Font Size')),
                ('fontColor', models.CharField(max_length=50, verbose_name='Font Color')),
                ('fontFamily', models.CharField(max_length=50, verbose_name='Font Family')),
                ('letterSpacing', models.CharField(max_length=50, verbose_name='Letter Spacing')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
