# Generated by Django 5.1.6 on 2025-03-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_formatdocument_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatdocument',
            name='lineSpacing',
            field=models.CharField(default=1, max_length=50, verbose_name='Line Spacing'),
            preserve_default=False,
        ),
    ]
