# Generated by Django 5.1.6 on 2025-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_formatdocument_linespacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='lecturer',
            field=models.CharField(default=1, max_length=100, verbose_name='lecturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approve', 'NotApprove')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
