from django.urls import path
from . import views


urlpatterns = [
    path("repo/login", views.Myhome, name="Myhome"),
    path("repo/logout", views.logout, name="logout"),
    path("repo/yes", views.yes, name="yes"),
    path("repo/forgetpassword", views.forgetpassword, name="forgetpassword"),
    path("repo/resetpassword", views.resetpassword, name="resetpassword"),
    path("repo/buttonClickreset", views.buttonClickreset, name="buttonClickreset"),
    path("repo/resendcode/", views.resendcode, name="resendcode"),
    path("repo/create_event/", views.create_event, name="create_event"),
    path("repo/dashboard/", views.dashboard, name="dashboard"),
    path("repo/uploadproject/", views.uploadproject, name="uploadproject"),
    path("repo/projectfolder/", views.projectfolder, name="projectfolder"),
    path("repo/updateProfile/", views.updateProfile, name="updateProfile"),
    path("repo/uploadDocProject/<int:id>", views.uploadDocProject, name="uploadDocProject"),
    path("repo/geteachDio/<int:id>", views.geteachDio, name="geteachDio"),
    path("repo/delete_folder/<int:id>", views.delete_folder, name="delete_folder"),
    path("repo/deletefolder/<int:id>", views.deletefolder, name="deletefolder"),
    path("repo/upload_file_view/", views.upload_file_view, name="upload_file_view"),
    path("repo/renamefolder/", views.renamefolder, name="renamefolder"), 
    path("repo/document/", views.document, name="document"),   
    path("repo/message/<int:id>", views.message, name="message"),   
    path("repo/viewmessage/<int:id>", views.viewmessage, name="viewmessage"),
    path("repo/draftmessages/", views.draftmessages, name="draftmessages"),
    path("repo/chat/", views.chat, name="chat"),
    path("repo/todos/<int:id>", views.todos, name="todos"),
    path("repo/deleteUser/<int:id>", views.deleteUser, name="deleteUser"),
    
    path("repo/mychat/", views.mychat, name="mychat"),
    path("repo/chatroom/", views.chatroom, name="chatroom"),
    path("repo/schedule_meeting/", views.schedule_meeting, name="schedule_meeting"),
    path("repo/get_chat_history/", views.get_chat_history, name="get_chat_history"),
    path("repo/deletemessages/<int:id>", views.deletemessages, name="deletemessages"),
    path("repo/deletemymessage/<int:id>", views.deletemymessage, name="deletemymessage"),
    path("repo/deleteCalender/<int:id>", views.deleteCalender, name="deleteCalender"),
    path("repo/activities", views.activities, name="activities"),
    path("repo/calendar", views.calendar, name="calendar"),
    path('repo/add_user/', views.add_user, name='add_user'),
    path("repo/deleteTodo/<int:id>", views.deleteTodo, name="deleteTodo"),
    path("repo/showSuggest/", views.showSuggest, name="showSuggest"),
    path("repo/upload/", views.upload_document, name="upload_document"),
    path("repo/documents/", views.document_list, name="document_list"),
]
